http:
  routers:
    gitea:
      rule: Host(`gitea.czy21.com`)
      service: gitea@docker
    grafana:
      rule: Host(`grafana.czy21.com`)
      service: grafana@docker
    consul:
      rule: Host(`consul.czy21-internal.com`)
      service: consul@docker
    gradle-build-cache:
      rule: Host(`gbc.czy21-internal.com`)
      service: gradle-build-cache@docker
    jenkins:
      rule: Host(`jenkins.czy21.com`)
      service: jenkins@docker
    jms:
      rule: Host(`jms.czy21-internal.com`)
      service: jms@docker
    nacos:
      rule: Host(`nacos.czy21-internal.com`)
      service: nacos@docker
    seata:
      rule: Host(`seata.czy21-internal.com`)
      service: seata@docker
    yearning:
      rule: Host(`yearning.czy21-internal.com`)
      service: yearning@docker
    sonarqube:
      rule: Host(`sonarqube.czy21-internal.com`)
      service: sonarqube@docker
    prometheus:
      rule: Host(`prom-{{ param_cluster_name }}.czy21.com`)
      service: prometheus@docker
    node-red:
      rule: Host(`node-red.czy21-internal.com`)
      service: node-red@docker
    drawio:
      rule: Host(`drawio.czy21-internal.com`)
      service: drawio@docker
    xxl-job:
      rule: Host(`xxl-job-dev.czy21.com`)
      service: xxl-job@docker      