
pipeline{
    agent any
    environment {
        GRADLE_HOME = "/var/jenkins_home/tools/gradle-7.1"
        PATH = "${GRADLE_HOME}/bin:${env.PATH}"
        PROJECT_ROOT="${WORKSPACE}/code/api"
        PROJECT_MODULE="portal"
    }
    parameters {
    gitParameter branchFilter: 'origin/(.*)', name: 'BRANCH', type: 'PT_BRANCH'
  }
    stages {
        stage('clone'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: "${BRANCH}"]], extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: false]], userRemoteConfigs: [[credentialsId: 'bruce', url: 'git@gitee.com:czyhome/erp.git']]])
            }
        }
        stage('build'){
            steps{
                sh 'chmod +x ${PROJECT_ROOT}/gradlew && ${PROJECT_ROOT}/gradlew --init-script ${GRADLE_HOME}/init.d/init.gradle --build-file ${PROJECT_ROOT}/build.gradle ${PROJECT_MODULE}:clean ${PROJECT_MODULE}:build -x test'
                sh 'docker build --tag registry:5000/${PROJECT_MODULE}:${BRANCH} --file ${PROJECT_ROOT}/${PROJECT_MODULE}/Dockerfile ${PROJECT_ROOT}/${PROJECT_MODULE}/ --no-cache --force-rm'
                sh 'docker push registry:5000/${PROJECT_MODULE}:${BRANCH}'
            }
        }
    }
}