node{
    GRADLE_HOME = '/var/jenkins_home/tools/gradle-7.1'
        env.PATH = "${GRADLE_HOME}/bin:${env.PATH}"
        env.WORK_DIR = pwd()

        stage('clone'){
				script {
checkout([$class: 'GitSCM', branches: [[name: 'dev-bruce']], extensions: [[$class: 'SubmoduleOption', disableSubmodules: false, parentCredentials: true, recursiveSubmodules: true, reference: '', trackingSubmodules: false]], userRemoteConfigs: [[credentialsId: 'bruce', url: 'git@gitee.com:czyhome/erp.git']]])
				}
        }
        stage('build'){
            sh '${WORK_DIR}/code/api/gradlew --init-script ${WORK_DIR}/script/template/java/init.gradle --build-file ${WORK_DIR}/code/api/build.gradle portal:clean portal:build -x test'
        }

}