#!/bin/sh /etc/rc.common  
# Copyright (C) 2007 OpenWrt.org  
START=99

start() {  
    ssh -qfN -o "StrictHostKeyChecking no" -i /root/softium-bruce -D 192.168.1.1:40200 tunnel@tunnel.softium.cn
}

stop() {  
    killall ssh  
}