- name: mongo conf
  template: src=files/mongod.cnf dest={{ role_path }}/mongod.cnf
  tags:
    - "svc-mongo-conf"
    - "svc-mongo"

- name: mongo conf
  shell: cat {{ role_path }}/mongod.conf | sudo tee /etc/mongod.conf > /dev/null && sudo chmod 644 /etc/mongod.conf
  tags:
    - "svc-mongo-conf"
    - "svc-mongo"

- name: mongo install
  shell: sh {{ param_remote_role_path }}/{{ param_ansible_os_family }}-mongo.sh
  tags:
    - "svc-mongo"