- name: cockpit
  shell: sh {{ param_remote_role_path }}/{{ param_ansible_os_family }}-cockpit.sh
  tags:
    - "svc-cockpit"

- name: nginx
  shell: sh {{ param_remote_role_path }}/{{ param_ansible_os_family }}-nginx.sh
  tags:
    - "svc-nginx"