

services:
  server:
    image: registry.czy21.com/openwrt/asu:self # docker.io/openwrt/asu:latest
    pull_policy: always
    command: uv run uvicorn --host 0.0.0.0 --reload --reload-include asu.toml asu.main:app
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/conf/asu.toml:/app/asu.toml:ro
      - {{ param_docker_data }}/{{ param_role_name }}/data/public/store:/public/store:ro
    env_file: {{ param_role_output_path }}/.env
    ports:
      - "8000:8000"
    restart: always

  worker:
    image: registry.czy21.com/openwrt/asu:self
    pull_policy: always
    command: uv run rqworker --logging_level INFO
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/conf/asu.toml:/app/asu.toml:ro
      - {{ param_docker_data }}/{{ param_role_name }}/data/public:/public:rw
      - /run/user/1000/podman/podman.sock:/var/podman.sock:rw
    env_file: {{ param_role_output_path }}/.env
    restart: always
    deploy:
      replicas: 3

networks:
  default:
    name: asu-build
    external: true