---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: ops
spec:
  rules:
    - host: prom-{{ .Values.param_cluster_name }}.czy21.com
      http:
        paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: prometheus
              port:
                number: 9090
    - host: xxl-job-{{ .Values.param_cluster_name }}.czy21.com
      http:
        paths:
          - backend:
              service:
                name: xxl-job
                port:
                  number: 8080
            path: /
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: cattle-system
spec:
  rules:
    - host: rancher-{{ .Values.param_cluster_name }}.czy21.com
      http:
        paths:
          - backend:
              service:
                name: rancher
                port:
                  number: 80
            path: /
            pathType: Prefix