{
 "title": "k8s",
 "description": "【中文版本】2021.10.10更新，kubernetes资源全面展示！包含K8S整体资源总览、微服务资源明细、Pod资源明细及K8S网络带宽，优化重要指标展示。https://github.com/starsliao/Prometheus",
 "tags": [
  "StarsL.cn",
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "originPrometheus",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_labels,origin_prometheus)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(kube_node_labels{origin_prometheus=~\"$originPrometheus\"},node)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{origin_prometheus=~\"$originPrometheus\"},namespace)"
    }
   },
   {
    "name": "container",
    "label": "Service(Container)",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$originPrometheus\",namespace=~\"$namespace\"},container)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{origin_prometheus=~\"$originPrometheus\",namespace=~\"$namespace\",container=~\"$container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "节点资源总览：所选节点:【$node】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "节点内存比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "内存限制率"
    }
   ]
  },
  {
   "title": "节点CPU比例",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}[2m])) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU请求率"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "CPU限制率"
    }
   ]
  },
  {
   "title": "节点与Pod",
   "type": "bargauge",
   "description": "集群节点数，节点POD数，节点POD上限",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_labels{origin_prometheus=~\"$originPrometheus\"})",
     "legendFormat": "节点数"
    },
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$originPrometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$node$\"})",
     "legendFormat": "Pod数"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})",
     "legendFormat": "上限Pod"
    }
   ]
  },
  {
   "title": "命名空间",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$originPrometheus\",node=~\"^$node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{origin_prometheus=~\"$originPrometheus\"}) by(namespace)"
    },
    {
     "expr": "count(count(kube_pod_container_info{origin_prometheus=~\"$originPrometheus\"}) by(container,namespace))by(namespace)"
    },
    {
     "expr": "count(kube_configmap_info{origin_prometheus=~\"$originPrometheus\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{origin_prometheus=~\"$originPrometheus\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$namespace：网络总览（关联节点与命名空间）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (rate(container_network_receive_bytes_total{origin_prometheus=~\"$originPrometheus\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "接收"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{origin_prometheus=~\"$originPrometheus\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m]))*8",
     "legendFormat": "发送"
    }
   ]
  },
  {
   "title": "节点内存信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})",
     "legendFormat": "总内存"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点CPU核数",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})",
     "legendFormat": "总核数"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",id=\"/\",node=~\"^$node$\"}[2m]))",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "请求量"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})",
     "legendFormat": "限制量"
    }
   ]
  },
  {
   "title": "节点存储信息",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) / sum (container_fs_limit_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "使用量"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})",
     "legendFormat": "总量"
    }
   ]
  },
  {
   "title": "$node：节点信息明细",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(kube_pod_info{origin_prometheus=~\"$originPrometheus\",created_by_kind!~\"<none>|Job\",node=~\"^$node$\"}) by (node)",
     "legendFormat": "pod数"
    },
    {
     "expr": "kube_node_status_condition{origin_prometheus=~\"$originPrometheus\",status=\"true\",node=~\"^$node$\"}  == 1",
     "legendFormat": "状态"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU使用%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "CPU请求%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)",
     "legendFormat": "内存限制%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node) / sum (container_fs_limit_bytes{origin_prometheus=~\"$originPrometheus\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$node$\"})by (node)",
     "legendFormat": "磁盘使用%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"pods\", unit=\"integer\",node=~\"^$node$\"})by (node)",
     "legendFormat": "Pod上限"
    }
   ]
  },
  {
   "title": "$node：节点CPU明细",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\", node=~\"^$node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node：节点内存明细",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container!=\"\",node=~\"^$node$\"})by (node) / sum(kube_node_status_allocatable{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\", node=~\"^$node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$node：节点网络总览",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "binbps" }
   ],
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{origin_prometheus=~\"$originPrometheus\",node=~\"^$node$\"}[2m]))by (node) *8",
     "legendFormat": "流入:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{origin_prometheus=~\"$originPrometheus\",node=~\"^$node$\"}[2m]))by (node) *8",
     "legendFormat": "流出:{{node}}"
    }
   ]
  },
  {
   "title": "微服务(容器名)资源总览：所选微服务:【$container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "微服务(容器名)资源统计",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container)",
       "legendFormat": "整体核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100",
       "legendFormat": "平均内存%(RSS)"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)",
       "legendFormat": "总内存使用(RSS) "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)"
      },
      {
       "expr": "count(kube_pod_container_info{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by(container,namespace) - 0"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体CPU使用率(最大100%)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}/100000) by (container)) * 100",
       "legendFormat": "{{ container}}"
      }
     ]
    },
    {
     "title": "微服务(容器名)整体内存使用率",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100",
       "legendFormat": "WSS：{{ container }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"}) by (container) * 100",
       "legendFormat": "RSS：{{ container }}"
      }
     ]
    },
    {
     "title": "微服务(容器名)每秒网络带宽 (可关联节点)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$originPrometheus\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$node$\",namespace=~\"$namespace\",pod=~\".*$container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "流入:{{ container }}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$originPrometheus\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$node$\",namespace=~\"$namespace\",pod=~\".*$container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(container) *8",
       "legendFormat": "流出:{{ container }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod资源总览：所选Pod:【$pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "$node：Pod资源明细(可关联节点)",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}/100000) by (container, pod,node,namespace)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container =~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"cpu\", unit=\"core\",pod=~\"$pod\",container =~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod,node,namespace)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container =~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{origin_prometheus=~\"$originPrometheus\",resource=\"memory\", unit=\"byte\",pod=~\"$pod\",container =~\"$container\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",namespace=~\"$namespace\"} * on (pod) group_left(node) kube_pod_info{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",node=~\"^$node$\",namespace=~\"$namespace\"}"
      }
     ]
    },
    {
     "title": "Pod容器CPU使用率(最大100%可关联节点)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}[2m])) by (container, pod) / (sum(container_spec_cpu_quota{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}/100000) by (container, pod)) * 100",
       "legendFormat": "{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod容器内存使用率(可关联节点)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
       "legendFormat": "WSS：{{ pod }}"
      },
      {
       "expr": "sum (container_memory_rss{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod)/ sum(container_spec_memory_limit_bytes{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",container =~\"$container\",container !=\"\",container!=\"POD\",node=~\"^$node$\",namespace=~\"$namespace\"}) by (container, pod) * 100",
       "legendFormat": "RSS：{{ pod }}"
      },
      {
       "expr": "(cass_jvm_heap{service=~\"$container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",namespace=~\"$namespace\"}) / (cass_jvm_heap_max{service=~\"$container\"} * on (pod_ip) group_right(service) kube_pod_info{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",namespace=~\"$namespace\"}) * 100",
       "legendFormat": "Heap：{{ pod }}"
      }
     ]
    },
    {
     "title": "Pod每秒网络带宽 (可关联节点)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "binbps" }
     ],
     "targets": [
      {
       "expr": "sum(sum(irate(container_network_receive_bytes_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$node$\",namespace=~\"$namespace\",pod=~\".*$container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(pod) *8",
       "legendFormat": "流入:{{ pod}}"
      },
      {
       "expr": "sum(sum(irate(container_network_transmit_bytes_total{origin_prometheus=~\"$originPrometheus\",pod=~\"$pod\",image!=\"\",name=~\"^k8s_.*\",node=~\"^$node$\",namespace=~\"$namespace\",pod=~\".*$container.*\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info) by(pod) *8",
       "legendFormat": "流出:{{ pod}}"
      }
     ]
    }
   ]
  }
 ]
}