{
 "title": "traefik",
 "description": "Simple dashboard for Traefik 2",
 "tags": [
  "traefik",
  "load-balancer",
  "docker",
  "prometheus"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job:",
    "query": {
     "query": "label_values(process_start_time_seconds{job=~\"traefik\"}, job)"
    }
   },
   {
    "name": "node",
    "query": {
     "query": "label_values(process_start_time_seconds{job=~\"$job\"}, instance)"
    }
   },
   {
    "name": "service",
    "label": "Service:",
    "query": {
     "query": "label_values(traefik_service_requests_total{instance=~\"$node\"}, service)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "404 Error Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{instance=~\"$node\",code=\"404\",protocol=~\"$protocol\",service=~\"$service\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{instance=~\"$node\",protocol=~\"$protocol\",service=~\"$service\"}) by (code))"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{instance=~\"$node\"}) / sum(traefik_entrypoint_requests_total{instance=~\"$node\"}) * 1000"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{instance=~\"$node\",protocol=~\"$protocol\",service=~\"$service\"}) / sum(traefik_entrypoint_requests_total{instance=~\"$node\",protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Bad Status Code Count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{instance=~\"$node\",code=\"404\",method=\"GET\",protocol=~\"$protocol\",service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{instance=~\"$node\",service=~\"$service\"}[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Used sockets",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{instance=~\"$node\",protocol=~\"http|https\",service=~\"$service\"}[$interval])) by (service)",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "ENTRYPOINT - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_open_connections{instance=~\"$node\"}) by (method)"
    }
   ]
  },
  {
   "title": "SERVICE - Open Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{instance=~\"$node\",service=~\"$service\"}) by (method)"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{instance=~\"$node\",protocol=~\"$protocol\",service=~\"$service\"}[$interval])) by (code)"
    }
   ]
  }
 ]
}