services:
  registry:
    image: registry:3.1.1
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/var/lib/registry
    environment:
      REGISTRY_LOG_LEVEL: info
    restart: always