x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.{{ param_role_name }}.service: {{ param_role_name }}
  traefik.http.services.{{ param_role_name }}.loadbalancer.server.port: 5000

services:
  registry:
    image: registry:3
    container_name: registry
    labels:
      <<: *traefik-label
    ports:
      - 5000:5000
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/var/lib/registry
      - {{ param_docker_data }}/{{ param_role_name }}/conf/auth/htpasswd:/auth/htpasswd
    environment:
      REGISTRY_LOG_LEVEL: info
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    restart: always