
# Loads default set of integrations. Do not remove.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0

# logger:
#   default: info
#   logs: 
#     custom_components.xiaomi_miot: debug

recorder: !include recorder.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
homekit: !include homekit.yaml
remote_homeassistant: !include remote_homeassistant.yaml