mirrors:
  docker.io:
    endpoint:
      - "https://{{ param_registry_proxy }}"
  {{ param_registry_proxy }}:
    endpoint:
      - "https://{{ param_registry_proxy }}"
  {{ param_registry }}:
    endpoint:
      - "https://{{ param_registry }}"