

services:
  server:
    image: "docker.io/openwrt/asu:latest"
    build:
      context: .
      dockerfile: Containerfile
    command: uv run uvicorn --host 0.0.0.0 asu.main:app
    volumes:
      - $PUBLIC_PATH/store:$PUBLIC_PATH/store:ro
      - $PUBLIC_PATH/key:$PUBLIC_PATH/key:ro
    ports:
      - "8000:8000"
    env_file: .env
    restart: always

  worker:
    image: "docker.io/openwrt/asu:latest"
    build:
      context: .
      dockerfile: Containerfile
    command: uv run rqworker --logging_level INFO
    volumes:
      - $PUBLIC_PATH:$PUBLIC_PATH:rw
      - $CONTAINER_SOCKET_PATH:$CONTAINER_SOCKET_PATH:rw
    env_file: .env
    restart: always
    deploy:
      replicas: 3