ARG BASE_IMAGE=registry.czy21.com/library/python-3.13

FROM $BASE_IMAGE

COPY ./build/ /app/

RUN python3 -m venv .pyenv && .pyenv/bin/python3 -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ -r requirements.txt