FROM python:3.9.17-slim-bullseye

LABEL org.opencontainers.image.url='https://github.com/czy21/container'
LABEL org.opencontainers.image.source='https://github.com/czy21/container/tree/main/mkdoc'
LABEL org.opencontainers.image.title='based on python:3.9.17-slim-bullseye'
LABEL org.opencontainers.image.authors='a805899926@gmail.com>'

WORKDIR /app

RUN pip install mkdocs mkdocs-material