server {
    http2 on;
    listen      443 ssl;
    server_name wxbatch.czy21.com;

    include /etc/nginx/conf.d/czy21-ssl.conf;

    location / {
        proxy_http_version 1.1;
        include /etc/nginx/snippets/app-proxy.conf;

        proxy_pass http://192.168.20.13:8081;
    }
    location /ws {
        proxy_http_version 1.1;
        include /etc/nginx/snippets/app-proxy.conf;

        proxy_pass http://192.168.20.13:9091;

    }
}

server {
    http2 on;
    listen      443 ssl;
    server_name wxbatch-demo.czy21.com;

    include /etc/nginx/conf.d/czy21-ssl.conf;

    location / {
        proxy_http_version 1.1;
        include /etc/nginx/snippets/app-proxy.conf;

        proxy_pass http://127.0.0.1:8081;
    }
    location /ws {
        proxy_http_version 1.1;
        include /etc/nginx/snippets/app-proxy.conf;

        proxy_pass http://127.0.0.1:9091;

    }
}