FROM registry.czy21-internal.com/library/ubuntu-openwrt-base

RUN apt install -y build-essential clang flex g++ gawk gcc-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev file wget qemu-utils libelf-dev
RUN apt-get clean