plugins {
    id 'groovy'
    id 'org.springframework.boot' version '4.0.3'
}

apply plugin: 'io.spring.dependency-management'

group 'org.ops'
version '1.0.0-SNAPSHOT'

repositories {
    maven {
        url "https://repo.jenkins-ci.org/public/"
    }
}

dependencyManagement {
    imports {
        mavenBom "io.jenkins.tools.bom:bom-2.580.x:7020.vf38cb_40380d1"
    }
    dependencies {
        dependency "org.apache.groovy:groovy:5.1.2"
    }
}

dependencies {
    implementation 'org.apache.groovy:groovy'
    implementation "org.jenkins-ci.plugins.workflow:workflow-cps"

}

sourceSets {
    main {
        groovy {
            srcDirs = ['src', "vars"]
        }
        resources {
            srcDirs = ['resources']
        }
    }

    test {
        groovy {
            srcDirs = ['test']
        }
    }

}