server {
    http2 on;
    listen      443 ssl;
    listen     8443 ssl;
    server_name nexus.czy21.com
                registry.czy21.com
                registry-proxy.czy21.com
                openwrt-download.czy21.com
                openwrt-firmware.czy21.com
                minio.czy21.com
                minio-web.czy21.com
                rustfs.czy21.com
                rustfs-web.czy21.com;

    include /etc/nginx/conf.d/czy21-ssl.conf;
    
    client_max_body_size 0;

    location / {
        
        include /etc/nginx/snippets/app-proxy.conf;

        proxy_pass http://192.168.20.2:80;
    }
}