http:
  routers:
    bitwarden:
      rule: Host(`bitwarden.czy21.com`)
      service: bitwarden@docker
    authentik:
      rule: Host(`authentik.czy21.com`)
      service: authentik@docker
    casdoor:
      rule: Host(`casdoor.czy21.com`)
      service: casdoor@docker