argo-workflows:
  fullnameOverride: argo-workflows
  crds:
    upgradeJob:
      image:
        repository: '{{ param_registry_proxy_url }}/kubectl'
  controller:
    image:
      registry: '{{ param_registry_proxy_url }}'
    workflowNamespaces: []
    workflowDefaults: 
      spec:
        serviceAccountName: argo-workflows-admin
  server:
    image:
      registry: '{{ param_registry_proxy_url }}'
  executor:
    image:
      registry: '{{ param_registry_proxy_url }}'