x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.{{ param_role_name }}.service: {{ param_role_name }}
  traefik.http.services.{{ param_role_name }}.loadbalancer.server.port: 7575

services:
  homarr:
    image: {{ param_registry_proxy if param_proxy and param_registry_proxy else 'ghcr.io' }}/homarr-labs/homarr:v1.77.2
    container_name: homarr
    labels:
      <<: *traefik-label
    privileged: true
    user: root
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/appdata/
    environment:
      SECRET_ENCRYPTION_KEY: "{{ param_homarr_key }}"
      # DB_DRIVER: mysql2
      # DB_DIALECT: mysql
      # DB_URL: mysql://{{ param_db_mysql_username }}:{{ param_db_mysql_password }}@{{ param_db_mysql_host }}:{{ param_db_mysql_port }}/homarr
    restart: always