
x-authentik-common: &authentik-common
  image: authentik/server:{{ param_authentik_version }}
  privileged: true
  user: root
  environment:
    AUTHENTIK_POSTGRESQL__NAME: authentik
    AUTHENTIK_POSTGRESQL__HOST: {{ param_db_pgsql_host }}
    AUTHENTIK_POSTGRESQL__PORT: {{ param_db_pgsql_port }}
    AUTHENTIK_POSTGRESQL__USER: {{ param_db_pgsql_username }}
    AUTHENTIK_POSTGRESQL__PASSWORD: {{ param_db_pgsql_password }}
    AUTHENTIK_SECRET_KEY: {{ param_authentik_secret_key }}
  restart: always

x-traefik-label: &traefik-label
  traefik.enable: true
  traefik.http.routers.{{ param_role_name }}.service: {{ param_role_name }}
  traefik.http.services.{{ param_role_name }}.loadbalancer.server.port: 9000

services:
  authentik-server:
    <<: *authentik-common
    container_name: authentik-server
    labels:
      <<: *traefik-label
    ports:
      - "9000:9000"
    volumes:
      - {{ param_docker_data }}/{{ param_role_name }}/conf/templates:/templates
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/data
    command: server

  authentik-worker:
    <<: *authentik-common
    container_name: authentik-worker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - {{ param_docker_data }}/{{ param_role_name }}/conf/templates:/templates
      - {{ param_docker_data }}/{{ param_role_name }}/data/:/data
    command: worker

  authentik-ldap:
    image: authentik/ldap:{{ param_authentik_version }}
    container_name: authentik-ldap
    ports:
        - 3389:3389
        - 6636:6636
    environment:
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: KHBLUruTxYoEofHCxZ48pZdikdoN0jr6n5TGii2wNt0GSpLbnPFFqH5xdfdx
    restart: always

  authentik-radius:
    image: authentik/radius:{{ param_authentik_version }}
    container_name: authentik-radius
    ports:
      - 1812:1812/udp
    environment:
      AUTHENTIK_HOST: http://authentik-server:9000
      AUTHENTIK_INSECURE: "true"
      AUTHENTIK_TOKEN: wePAbJ4ulUWXVjRCZJNE7EIjLWsaRU5U9kduF5eyT1ZuGXyCrJVsNrOIoNT6
    restart: always