apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-artifact-credentials
data:
  accessKey: {{ .Values.param_s3_access_key | b64enc }}
  secretKey: {{ .Values.param_s3_secret_key | b64enc }}