apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ index .Values "argo-workflows" "fullnameOverride" }}-admin
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "argo-workflows" "fullnameOverride" }}-admin.service-account-token
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ index .Values "argo-workflows" "fullnameOverride" }}-admin
type: kubernetes.io/service-account-token  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ index .Values "argo-workflows" "fullnameOverride" }}-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ index .Values "argo-workflows" "fullnameOverride" }}-admin
    namespace: {{ .Release.Namespace }}