name: Build

on:
  push:
    paths:
      - server/docker/**
      - server/chart/**
  workflow_dispatch:
    inputs:
      targets:
        type: string

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build-docker:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build server/docker
        run: |

          PATHS=(
              server/docker/app/hugo
              server/docker/app/mkdoc
              server/docker/app/nginx-spa
              server/docker/ops/jenkins
              server/docker/ops/jenkins-ssh-agent
              server/docker/ops/jenkins-inbound-agent
              server/docker/sdk/dotnet
              server/docker/sdk/java
              server/docker/sdk/nodejs
              server/docker/sdk/python
          )

          source=server/docker
          TARGETS="${{ inputs.targets }}"
          if [ "${{ github.event_name }}" = "push" ];then
            DIFFS=$(git diff --diff-filter=d --name-only HEAD~)
  
            for ROOT in "${PATHS[@]}"; do
              for CHANGE in $DIFFS; do
                if [[ "$CHANGE" == "$ROOT"* ]]; then
                  TARGETS+="${ROOT#"$source/"} "
                  break
                fi
              done
            done
          fi
          echo "Build $TARGETS"
          if [ -n "$TARGETS" ]; then
            (cd $source;PYTHONPATH=../.. $HOME/.python3/bin/python3 -B main.py build --roles $TARGETS --target Dockerfile --push -p param_registry_targets=docker --parallel)
          fi
          echo

  build-chart:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build server/chart
        run: |

          PATHS=(
              server/chart/app/dotnet
              server/chart/app/go
              server/chart/app/java
              server/chart/app/python
              server/chart/app/web
          )

          source=server/chart
          TARGETS="${{ inputs.targets }}"
          if [ "${{ github.event_name }}" = "push" ];then
            DIFFS=$(git diff --diff-filter=d --name-only HEAD~)
  
            for ROOT in "${PATHS[@]}"; do
              for CHANGE in $DIFFS; do
                if [[ "$CHANGE" == "$ROOT"* ]]; then
                  TARGETS+="${ROOT#"$source/"} "
                  break
                fi
              done
            done
          fi
          echo "Build $TARGETS"
          if [ -n "$TARGETS" ]; then
            (cd $source;PYTHONPATH=../.. $HOME/.python3/bin/python3 -B main.py build --roles $TARGETS --target Chart --push --parallel)
          fi
          echo