name: Deploy doc

on:
  push:
    paths:
      - server/docker/**
      - server/chart/**
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: |
          rm -rf cd $HOME/container/
          $HOME/.python3/bin/python3 -m pip install -r server/requirements.txt
          $HOME/.python3/bin/python3 -m pip install mkdocs mkdocs-material
          $HOME/.python3/bin/python3 -B main.py
      - name: Push to container repository
        run: |
          cd $HOME/container/
          if [ -n "$(git status -s)" ];then
            git add . && git commit --amend -m "CI: sync code" && git push --force
          fi
      - name: Build with Mkdocs
        run: $HOME/.python3/bin/mkdocs build -d build/doc
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build/doc --project-name=doc