---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io/path: "actuator/prometheus"
spec:
  selector:
    app: {{ include "app.fullname" . }}
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
spec:
  replicas: {{ .Values.param_replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ include "app.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "app.fullname" . }}
    spec:
      containers:
        - name: {{ include "app.fullname" . }}
          image: "{{ .Values.param_registry }}/{{ .Values.param_registry_dir }}/{{ include "app.fullname" . }}:{{ .Values.param_release_version }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TZ
              value: Asia/Shanghai
            - name: DOTNET_OPTS
              value: {{ .Values.param_app_args }}
          volumeMounts:
            - name: data
              mountPath: /app/data/
              subPath: data
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.param_data_claim_name }}